name: Build images
on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        base_distro: [
          almalinux-8.7,
          almalinux-9.1,
          debian-bullseye,
          fedora-36,
          fedora-37,
          leap-15.3,
          leap-15.4,
          ubuntu-18.04,
          ubuntu-20.04,
          ubuntu-22.04
        ]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Test
        uses: docker/build-push-action@v4
        with:
          target: test
          context: ${{ matrix.base_distro }}
          push: false
          
      - name: Development
        uses: docker/build-push-action@v4
        with:
          target: development
          context: ${{ matrix.base_distro }}
          push: false
